package ru.goodsReview.analyzer;

/**
 * Date: 16.02.12
 * Time: 00:34
 * Author:
 * Ilya Makeev
 * ilya.makeev@gmail.com
 */

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.LineNumberReader;
import java.net.URL;
import java.net.URLEncoder;

public class YaSearcher {
    private static final String YA_URL = "http://xmlsearch.yandex.ru/xmlsearch?";
    private static final String ENC = "UTF-8";
    private static final String AND = "&";

    private String user;
    private String key;

    /**
     * Constructor
     * @param user your Yandex username
     * @param key key generated by Yandex.XML
     */
    public YaSearcher(final String user, final String key) {
        this.user = user;
        this.key = key;
    }

    /**
     * Retrieve Yandex.XML response stream via GET request
     * @param query search query
     * @param pageNumber number of search page
     * @return Yandex.XML response stream
     * @throws IOException input/output exception
     */
    public InputStream retrieveResponseViaGetRequest(
            final String query,
            final int pageNumber
    ) throws IOException {

        final StringBuilder address = new StringBuilder(YA_URL);
        address.append("user=").append(user).append(AND)
                .append("key=").append(key).append(AND)
                .append("query=").append(URLEncoder.encode(query, ENC)).append(AND)
                .append("page=").append(pageNumber);
        final URL url = new URL(address.toString());
        return url.openStream();
    }


    public static void main(String[] args) throws IOException {
        final String user = "achugr";
        final String key = "03.105654139:7880f50b7f5479448228e3f18571cec8";
        final String query = "world";
        final int page = 0;

        LineNumberReader lineReader = null;
        try {
            final YaSearcher searcher = new YaSearcher(user, key);
            lineReader = new LineNumberReader(
                    new InputStreamReader(searcher.retrieveResponseViaGetRequest(query, page)));

            String line = lineReader.readLine();
            while (line!= null) {
                if(line.contains("found priority=\"all\"")){
                    String s1 =  line.substring(line.indexOf("found priority=\"all\"")-1);
                    System.out.println(s1.substring(0,s1.indexOf("/found")-1));
                }
                line = lineReader.readLine();
            }
        } finally {
            if (lineReader != null) {
                lineReader.close();
            }
        }
    }
}

